2015-12-10 01:11:02 Warning: Warning (4096): Argument 1 passed to App\Controller\UsersController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Event\EventManager.php on line 385 and defined in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 15]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 15
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 491
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-10 01:11:02 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 18]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 01:11:02 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /blog/users
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 01:12:31 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 18]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 01:12:31 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /blog/users
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 01:15:19 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 18]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 01:15:19 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /blog/users
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 01:18:07 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 17]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 01:18:07 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /blog/users
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 01:19:53 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 17]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 01:19:54 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /blog/users
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 01:21:42 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 25]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 01:21:42 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /blog/users
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 01:22:22 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 25]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 01:22:22 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /blog/users
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 01:29:42 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 27]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 01:29:43 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /blog/users
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 27)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 01:54:03 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 27]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 01:54:03 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /blog/users
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 27)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 01:57:34 Error: [Cake\Datasource\Exception\InvalidPrimaryKeyException] Record not found in table "users" with primary key [NULL]
Request URL: /blog/users/view
Stack Trace:
#0 C:\xampp\htdocs\blog\src\Controller\UsersController.php(36): Cake\ORM\Table->get(NULL, Array)
#1 [internal function]: App\Controller\UsersController->view()
#2 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#5 C:\xampp\htdocs\blog\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2015-12-10 02:12:35 Warning: Warning (4096): Argument 1 passed to App\Controller\UsersController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Event\EventManager.php on line 385 and defined in [C:\xampp\htdocs\blog\src\Controller\UsersController.php, line 89]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 89
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 491
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-10 02:15:26 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\login.ctp',
)
Request URL: /blog/users/login
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\blog\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-12-10 02:20:47 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\blog\src\Template\Users\login.ctp, line 2]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 02:20:47 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '<'
Request URL: /blog/users/login
Stack Trace:
#0 C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 2)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 03:38:12 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Login could not be found.
Exception Attributes: array (
  'class' => 'Login',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /blog/login
Stack Trace:
#0 C:\xampp\htdocs\blog\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-10 07:56:54 Warning: Warning (4096): Argument 1 passed to Cake\View\Helper\FormHelper::end() must be of the type array, string given, called in C:\xampp\htdocs\blog\src\Template\Articles\view.ctp on line 41 and defined in [C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\View\Helper\FormHelper.php, line 520]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
Cake\View\Helper\FormHelper::end() - CORE\src\View\Helper\FormHelper.php, line 520
include - APP/Template\Articles\view.ctp, line 41
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-10 07:57:08 Warning: Warning (4096): Argument 1 passed to Cake\View\Helper\FormHelper::end() must be of the type array, string given, called in C:\xampp\htdocs\blog\src\Template\Articles\view.ctp on line 41 and defined in [C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\View\Helper\FormHelper.php, line 520]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
Cake\View\Helper\FormHelper::end() - CORE\src\View\Helper\FormHelper.php, line 520
include - APP/Template\Articles\view.ctp, line 41
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-10 07:57:55 Warning: Warning (4096): Argument 1 passed to Cake\View\Helper\FormHelper::end() must be of the type array, string given, called in C:\xampp\htdocs\blog\src\Template\Articles\view.ctp on line 41 and defined in [C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\View\Helper\FormHelper.php, line 520]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
Cake\View\Helper\FormHelper::end() - CORE\src\View\Helper\FormHelper.php, line 520
include - APP/Template\Articles\view.ctp, line 41
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-10 07:59:36 Warning: Warning (4096): Argument 1 passed to Cake\View\Helper\FormHelper::end() must be of the type array, string given, called in C:\xampp\htdocs\blog\src\Template\Articles\view.ctp on line 39 and defined in [C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\View\Helper\FormHelper.php, line 520]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
Cake\View\Helper\FormHelper::end() - CORE\src\View\Helper\FormHelper.php, line 520
include - APP/Template\Articles\view.ctp, line 39
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-10 08:01:59 Warning: Warning (4096): Argument 1 passed to Cake\View\Helper\FormHelper::end() must be of the type array, string given, called in C:\xampp\htdocs\blog\src\Template\Articles\view.ctp on line 39 and defined in [C:\xampp\htdocs\blog\vendor\cakephp\cakephp\src\View\Helper\FormHelper.php, line 520]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
Cake\View\Helper\FormHelper::end() - CORE\src\View\Helper\FormHelper.php, line 520
include - APP/Template\Articles\view.ctp, line 39
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



